spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

data:
  web:
    pageable:
      size-parameter: size
      page-parameter: page
      default-page-size: 10
      one-indexed-parameters: false
      max-page-size: 2000
      prefix:
      qualifier-delimiter: _